repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        files: ^api/
        args: [--fix]
      - id: ruff-format
        files: ^api/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        files: ^api/src/
        args: ["--config-file=api/pyproject.toml"]
        additional_dependencies: ["fastapi>=0.115", "pydantic>=2.9", "nepkit>=0.4"]
